### PR TITLE
Small fix again

### PR DESCRIPTION
**Pull request by keirastanley**
You know what i did

### CODE REVIEW

**Review by rhonamackay — APPROVED** [review]
Gotta get my fix 💯💯💯

**Review by gregrutnam — APPROVED** [review]
Bless that wee little fix

**Comment by keirastanley** [comment]
Thanks for everything guys. Grateful for all the support. This has been the merge of a lifetime.

**Review by Suzi-Clark — APPROVED** [review]
The package is deployed. We know what to do next.

**Review by remiyeku — APPROVED** [review]
This isn't the only thing that's small....

**Pull request merged**
