### PR TITLE
Header is sticky on results and bar page and filters are all reset wh…

### PR DESCRIPTION
**Pull request by keirastanley**
…en location is changed from the header

### CODE REVIEW

**Review by rhonamackay — APPROVED** [review]
Definitely not a horrible mistake!

**Review by faseehahmed1 — APPROVED** [review]
Sticky situation... sounds awful

**Review by gregrutnam — APPROVED** [review]
Stick bugs getting into our code

**Comment by keirastanley** [comment]
> Stick bugs getting into our code

I'll have you know there are NO bugs in our code 😤

**Review by remiyeku — APPROVED** [review]
Sticky bars, something I'm very used to...

**Review by Suzi-Clark — APPROVED** [review]
🪲🚫 no bugs allowed - only sticky success 🏆🥇

**Pull request merged**
